### PR TITLE
add github action build and release

### PR DESCRIPTION
**Pull request by pyaillet**
Hi !

Thank you for this projet.

I noticed the current release is behind master.
Would you be interested with a minimal CI workflow to generate the apk from CI on releases ?
If so feel free to take this PR, if not, no problem you can close it :)

### CODE REVIEW

**Comment by Bellafaire** [comment]
I was never sure how to configure a build tool with github, thank you for the PR!

**Comment by Bellafaire** [comment]
Hi, Are there any additional steps required? I am unfamiliar with configuring this type of workflow and under the workflows tab it seems to skip the "release APK" step.

**Comment by pyaillet** [comment]
Oh sorry, I should have explained it as comment of my PR.

You need to push a tag in the format `v*` as you could see [here](https://github.com/Bellafaire/Android-Companion-App-For-BLE-Devices/blob/master/.github/workflows/build.yml#L44)

It creates the release and pushes the apk associated with it. It doesn't create the changelog though :\

**Comment by Bellafaire** [comment]
I see, got it to work. Thank you for the PR and your help!

**Pull request merged**
